import {
  Document,
  ChartData,
  Task,
  Warehouse,
  Product,
  StockMovement,
} from "./types";

export const MOCK_COMPANY_DATA = {
  name: "TechSolutions Adam Kowalski",
  nip: "1234567890",
  taxType: "Ryczałt 12%",
  vatPayer: true,
  currentMonthVat: 3450.5,
  currentMonthIncome: 12500.0,
  currentMonthCosts: 4200.0,
  projectedIncome: 14000.0,
  bankBalance: 45200.0,
};

export const MOCK_CHART_DATA: ChartData[] = [
  { month: "Sty", income: 10500, costs: 3800, balance: 6700 },
  { month: "Lut", income: 11200, costs: 4100, balance: 7100 },
  { month: "Mar", income: 10800, costs: 3900, balance: 6900 },
  { month: "Kwi", income: 12500, costs: 4200, balance: 8300 },
  { month: "Maj", income: 13100, costs: 4500, balance: 8600 },
  { month: "Cze", income: 11800, costs: 4000, balance: 7800 },
];

export const MOCK_EXPENSE_BREAKDOWN = [
  { name: "Podatki/ZUS", value: 4500, fill: "#10b981" },
  { name: "Leasingi", value: 2200, fill: "#f59e0b" },
  { name: "Oprogramowanie", value: 800, fill: "#ef4444" },
  { name: "Biuro", value: 1200, fill: "#8b5cf6" },
];

export const MOCK_DOCUMENTS: Document[] = [
  {
    id: "F/2024/05/01",
    contractor: "Cloud Services Sp. z o.o.",
    type: "Faktura",
    category: "Koszt",
    source: "KSeF",
    status: "Nieopłacone",
    amountNet: 1200.0,
    amountGross: 1476.0,
    dueDate: "2024-05-25",
    date: "2024-05-11",
    sharedWith: ["Księgowa Anna"],
    aiSummary:
      "Faktura za usługi chmurowe AWS/Azure. Wydatek standardowy, zgodny z historią. Pamiętaj o terminie 25 maja, aby uniknąć odsetek.",
  },
  {
    id: "P/2024/003",
    contractor: "Urząd Skarbowy",
    type: "Pismo urzędowe",
    category: "Urzędowe",
    source: "e-Doręczenia",
    status: "Oczekuje",
    amountNet: 0,
    amountGross: 0,
    dueDate: "2024-05-20",
    date: "2024-05-10",
    aiSummary:
      "Wezwanie do złożenia wyjaśnień w sprawie deklaracji VAT-7 za marzec. Urząd prosi o przesłanie skanów ewidencji zakupów. Masz na to 7 dni.",
  },
  {
    id: "FV/X-99",
    contractor: "Biuro Plus",
    type: "Faktura",
    category: "Koszt",
    source: "Email",
    status: "Opłacone",
    amountNet: 150.0,
    amountGross: 184.5,
    dueDate: "2024-05-15",
    date: "2024-05-08",
    sharedWith: ["Księgowa Anna", "Wspólnik Marek"],
    aiSummary:
      "Drobny zakup materiałów biurowych. Faktura została już opłacona kartą firmową. Dokument poprawny merytorycznie.",
  },
  {
    id: "F/2024/05/02",
    contractor: "Marketing Master",
    type: "Faktura",
    category: "Przychód",
    source: "KSeF",
    status: "Opłacone",
    amountNet: 2500.0,
    amountGross: 3075.0,
    dueDate: "2024-05-14",
    date: "2024-05-05",
    aiSummary:
      "Twoja faktura sprzedażowa za usługi marketingowe. Klient opłacił ją terminowo. Przychód zakwalifikowany do ryczałtu 12%.",
  },
];

export const MOCK_TASKS: Task[] = [
  { id: "1", title: "Opłać fakturę Cloud Services", completed: false },
  { id: "2", title: "Wyślij odpowiedź na e-Doręczenie z US", completed: false },
  { id: "3", title: "Zaktualizuj grafik na czerwiec", completed: true },
  { id: "4", title: "Zweryfikuj limity VAT na Q2", completed: false },
];

export const MOCK_WAREHOUSES: Warehouse[] = [
  {
    id: 1,
    name: "Magazyn Główny",
    location: "Warszawa, ul. Przemysłowa 15",
    capacity: 5000,
    usedCapacity: 3750,
    manager: "Jan Nowak",
    status: "Aktywny",
  },
  {
    id: 2,
    name: "Magazyn Północ",
    location: "Gdańsk, ul. Portowa 8",
    capacity: 3000,
    usedCapacity: 1200,
    manager: "Anna Wiśniewska",
    status: "Aktywny",
  },
  {
    id: 3,
    name: "Magazyn Południe",
    location: "Kraków, ul. Logistyczna 22",
    capacity: 2000,
    usedCapacity: 1900,
    manager: "Piotr Zieliński",
    status: "Konserwacja",
  },
  {
    id: 4,
    name: "Punkt Przeładunkowy",
    location: "Łódź, ul. Centralna 3",
    capacity: 800,
    usedCapacity: 150,
    manager: "Ewa Kowalczyk",
    status: "Aktywny",
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Laptop Dell Latitude 5540",
    sku: "EL-LAP-001",
    category: "Elektronika",
    quantity: 45,
    minQuantity: 10,
    unit: "szt.",
    priceNet: 3200,
    warehouseId: 1,
    warehouseName: "Magazyn Główny",
    lastRestocked: "2024-05-01",
  },
  {
    id: 2,
    name: 'Monitor Samsung 27"',
    sku: "EL-MON-002",
    category: "Elektronika",
    quantity: 8,
    minQuantity: 15,
    unit: "szt.",
    priceNet: 1100,
    warehouseId: 1,
    warehouseName: "Magazyn Główny",
    lastRestocked: "2024-04-20",
  },
  {
    id: 3,
    name: "Kabel USB-C 2m",
    sku: "AK-KAB-010",
    category: "Akcesoria",
    quantity: 320,
    minQuantity: 50,
    unit: "szt.",
    priceNet: 25,
    warehouseId: 1,
    warehouseName: "Magazyn Główny",
    lastRestocked: "2024-05-08",
  },
  {
    id: 4,
    name: "Papier A4 (ryza)",
    sku: "BIU-PAP-001",
    category: "Biuro",
    quantity: 150,
    minQuantity: 30,
    unit: "szt.",
    priceNet: 18,
    warehouseId: 2,
    warehouseName: "Magazyn Północ",
    lastRestocked: "2024-05-05",
  },
  {
    id: 5,
    name: "Toner HP 26A",
    sku: "BIU-TON-003",
    category: "Biuro",
    quantity: 3,
    minQuantity: 5,
    unit: "szt.",
    priceNet: 180,
    warehouseId: 2,
    warehouseName: "Magazyn Północ",
    lastRestocked: "2024-03-15",
  },
  {
    id: 6,
    name: "Mysz Logitech MX Master",
    sku: "AK-MYS-005",
    category: "Akcesoria",
    quantity: 22,
    minQuantity: 10,
    unit: "szt.",
    priceNet: 350,
    warehouseId: 1,
    warehouseName: "Magazyn Główny",
    lastRestocked: "2024-04-28",
  },
  {
    id: 7,
    name: "Klawiatura mechaniczna",
    sku: "AK-KLA-008",
    category: "Akcesoria",
    quantity: 0,
    minQuantity: 5,
    unit: "szt.",
    priceNet: 280,
    warehouseId: 3,
    warehouseName: "Magazyn Południe",
    lastRestocked: "2024-02-10",
  },
  {
    id: 8,
    name: "Switch sieciowy 24-port",
    sku: "NET-SWI-002",
    category: "Sieć",
    quantity: 12,
    minQuantity: 3,
    unit: "szt.",
    priceNet: 890,
    warehouseId: 1,
    warehouseName: "Magazyn Główny",
    lastRestocked: "2024-05-10",
  },
];

export const MOCK_MOVEMENTS: StockMovement[] = [
  {
    id: 1,
    productName: "Laptop Dell Latitude 5540",
    sku: "EL-LAP-001",
    type: "Przyjęcie",
    quantity: 20,
    warehouseTo: "Magazyn Główny",
    date: "2024-05-11",
    operator: "Jan Nowak",
    note: "Dostawa od Dell Polska",
  },
  {
    id: 2,
    productName: 'Monitor Samsung 27"',
    sku: "EL-MON-002",
    type: "Wydanie",
    quantity: 5,
    warehouseFrom: "Magazyn Główny",
    date: "2024-05-10",
    operator: "Jan Nowak",
    note: "Zamówienie klienta #1245",
  },
  {
    id: 3,
    productName: "Toner HP 26A",
    sku: "BIU-TON-003",
    type: "Przesunięcie",
    quantity: 2,
    warehouseFrom: "Magazyn Główny",
    warehouseTo: "Magazyn Północ",
    date: "2024-05-09",
    operator: "Anna Wiśniewska",
  },
  {
    id: 4,
    productName: "Klawiatura mechaniczna",
    sku: "AK-KLA-008",
    type: "Wydanie",
    quantity: 5,
    warehouseFrom: "Magazyn Południe",
    date: "2024-05-08",
    operator: "Piotr Zieliński",
    note: "Ostatnie sztuki – zamówić!",
  },
  {
    id: 5,
    productName: "Papier A4 (ryza)",
    sku: "BIU-PAP-001",
    type: "Przyjęcie",
    quantity: 100,
    warehouseTo: "Magazyn Północ",
    date: "2024-05-05",
    operator: "Anna Wiśniewska",
  },
  {
    id: 6,
    productName: "Kabel USB-C 2m",
    sku: "AK-KAB-010",
    type: "Zwrot",
    quantity: 10,
    warehouseTo: "Magazyn Główny",
    date: "2024-05-04",
    operator: "Jan Nowak",
    note: "Zwrot od klienta – towar sprawny",
  },
  {
    id: 7,
    productName: "Mysz Logitech MX Master",
    sku: "AK-MYS-005",
    type: "Inwentaryzacja",
    quantity: 22,
    warehouseTo: "Magazyn Główny",
    date: "2024-05-01",
    operator: "Jan Nowak",
    note: "Korekta po inwentaryzacji (+2)",
  },
];
